encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<title>", views.title, name="title"),
    path("search/", views.search, name="search"),
    path("newpage/", views.newpage, name="newpage"),
    path("<entry>/editpage", views.editpage, name="editpage"),
    path("<entry>/savepage", views.savepage, name="savepage"),
    path("random/", views.random, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponseRedirect
from django import forms
from django.shortcuts import render, redirect
from django.urls import reverse
from . import util
from random import randint
from markdown2 import markdown

class NewPageForm(forms.Form):
    pageName = forms.CharField(
        label='Title',
        widget=forms.TextInput(
            attrs={
                'name': 'title', 
                'id':'pageTitle',
                'placeholder': 'Enter a title for the page',
                'class': 'form-field'}))
    
    pageContent = forms.CharField(
        label='Content',
        widget=forms.Textarea(
            attrs={
                'name': 'content', 
                'placeholder': 'Enter a content for the page', 
                'class': 'form-field',
                'rows': '3', 
                'cols': '5'}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def title(request, title):
    content = util.get_entry(title)
    if content is None:
        content = "##Entry not found"

    content = markdown(content)
    return render(request, "encyclopedia/entry.html", {
        "title" : title, "content" : content
    })

def search(request):
    q = request.POST.get('q')
    if q in util.list_entries():
        return redirect("encyclopedia:title", title=q)
    return render(request, "encyclopedia/search.html", {"results": util.search(q), "q": q})

def newpage(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            pageName = form.cleaned_data['pageName']
            pageContent = form.cleaned_data['pageContent']
            if pageName in util.list_entries():
                pageContent = "##Title already exist. Try another one"
                pageContent = markdown(pageContent)
                return render(request, "encyclopedia/entry.html", {"title": pageName, "content": pageContent})
            util.save_entry(pageName, pageContent)
            return redirect("encyclopedia:title", title=pageName)
        else:
            return render(request, "encyclopedia/newpage.html", {
                "form" : form
            })
        
    return render(request, "encyclopedia/newpage.html", {
        "form" : NewPageForm()
    })

def editpage(request, entry):
    content = util.get_entry(entry)
    if content:
        return render(request, "encyclopedia/editpage.html",{
        "title": entry,
        "content" : util.get_entry(entry)
    })
    else:
        return HttpResponseRedirect(reverse('encyclopedia:index'))
    
def savepage(request, entry):
    if request.method == "POST":
        new_content = request.POST.get("content")
        util.save_entry(entry, new_content)
        return redirect("encyclopedia:title", entry)


def random(request):
    entries = util.list_entries()
    entry = entries[randint(0, len(entries)-1)]
    return redirect("encyclopedia:title", title=entry)

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ title }}
{% endblock %}

{% block body %}
    <h1>Edit {{ title }} Page</h1>

    <form action="{% url 'encyclopedia:savepage' title %}" method="POST">
        {% csrf_token %}

        <div class="input-area" style="margin-bottom: 10px;">
            <label for="id_title">Title:</label><br/>
            <input type="text" name="title" value="{{ title }}" id="id_title" readonly="" disabled="disabled"></p>
        </div>

        <div class="input-area" style="margin-bottom: 10px;">
            <label for="id_content">Content:</label><br/>
            <textarea name="content" style="height: 300px" required="required" id="id_content">{{ content }}</textarea>
        </p>
    </div>

    <button class="btn btn-primary" type="submit">Save</button>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title|safe }}
{% endblock %}

{% block body %}
    {{ content|safe }}
    <form action="{% url 'encyclopedia:editpage' title %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="entry_title" value="{{ title }}">
            <button class="btn btn-primary" type="submit">Edit page</button>

            <a href="{% url 'encyclopedia:index' %}" style="margin-left: 20px;">Go to the main page</a>
        </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li><a href="{% url 'encyclopedia:title' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
            <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet"></head>
            <body>
                <div class="row">
                    <div class="sidebar col-lg-2 col-md-3">
                        <h2>Wiki</h2>
                        <form action="{% url 'encyclopedia:search' %}" method="POST">
                            {% csrf_token %}
                            <input class="search" type="text" name="q" placeholder="Search Encyclopedia"></form>
                            <div>
                                <a href="{% url 'encyclopedia:index' %}">Home</a>
                            </div>
                            <div>
                                <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                            </div>
                            <div>
                                <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                            </div>
                            {% block nav %}
                            {% endblock %}
                        </div>
                        <div class="main col-lg-10 col-md-9">
                            <div class="container"> 
                                {% block body %}
                                {% endblock %}
                                </div>
                            </div>
                        </div>

                    </body>
                </html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1> <br>

    <form action="{% url 'encyclopedia:newpage' %}" method="POST">
        {% csrf_token %}

        {{ form }}
        <input type="submit" name="submitButton" id="btn" value="Submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <p style="font-size: 20px;">Here`s entries that you may have wanted to find:</p>
    <ul>
        {% for result in results %}
            <li>
                <a href="{% url 'encyclopedia:title' title=result %}">{{ result }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}